version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: event_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "5001:5001"

  frontend:
    build: ./frontend
    environment:
      - REACT_APP_BASE_URL=${REACT_APP_BASE_URL}
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
